---
esphome:
  name: my-room-air-quality-sensor

esp8266:
  board: d1_mini
  restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret wifi_ssid2
    password: !secret wifi_password2

captive_portal:

logger:

# home assistant api password
api:
  encryption:
    key: !secret api_key

# over the air update password
ota:
  platform: esphome
  password: !secret esp_cam_ota_password

# UART config for the pm1006 sensor
uart:
  rx_pin: D3
  baud_rate: 9600

# i2c config for the ccs811 sensor
i2c:
  sda: D2
  scl: D1

# sensor configuration
sensor:
  - platform: pm1006
    pm_2_5:
      name: "My room PM2.5"
  - platform: ccs811
    eco2:
      name: "My room eCO2"
    tvoc:
      name: "My room TVOC"
    address: 0x5A
    update_interval: 60s
    baseline: 0x02C4
